# Mode details about configuration
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - "gomod"
      - "dependencies"
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    labels:
      - "github-actions"
      - "dependencies"
    schedule:
      interval: monthly
