site_name: mkunion - strongly typed union types in Golang
repo_url: https://github.com/widmogrod/mkunion
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - content.action.edit

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true