name: CI
on: [ pull_request ]

jobs:
  test-go:
    name: Test implementation in Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.19
        id: go

      - run: cd cmd/mkunion; go get -v -t -d ./...
      - run: cd cmd/mkunion; go build -o mkunion

      - run: go get -v -t -d ./...
      - run: go generate ./...

      # initiate docker-compose services
      - run: |
          pip install awscli-local
      - run: dev/bootstrap.sh& sleep 10

      # run tests
      - run: go test -v ./...
