name: CI
on: [ pull_request ]

jobs:
  test-go:
    name: Test implementation in Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - run: cd cmd/mkunion; go get -v -t -d ./...
      - run: cd cmd/mkunion; go build -o mkunion

      - run: go get -v -t -d ./...
      - run: go generate ./...
      - run: go test -v ./...
