name: CI
on: [ pull_request ]

jobs:
  test-go:
    name: Test implementation in Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - run: cd cmd/mkunion; go get -v -t -d ./...
      - run: cd cmd/mkunion; go build -o mkunion

      - run: go get -v -t -d ./...
      - run: go generate ./...
      - run: go test -v ./...

  test-go-arm:
    name: Test implementation in Golang
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - run: cd cmd/mkunion; go get -v -t -d ./...
      - run: cd cmd/mkunion; go build -o mkunion

      - run: go get -v -t -d ./...
      - run: go generate ./...
      - run: go test -v ./...
